f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources src/main/proto/ClientProtos.proto src/main/proto/TajoMasterClientProtocol.proto src/main/proto/QueryMasterClientProtocol.proto  src/main/proto/RpcProtos.proto 
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/DataTypes.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/tajo_protos.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/TajoIdProtos.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/PrimitiveProtos.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/errors.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-common/src/main/proto/stacktrace.proto
f:\devel\proto\protoc -Isrc/main/proto/ --proto_path=../tajo-common/src/main/proto --proto_path=../tajo-catalog/tajo-catalog-common/src/main/proto --proto_path=../tajo-core/src/main/proto --cpp_out=src/generated-sources ../tajo-catalog/tajo-catalog-common/src/main/proto/CatalogProtos.proto

