// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TajoMasterClientProtocol.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "TajoMasterClientProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tajo {
namespace client {

namespace {


}  // namespace


void protobuf_AssignDesc_TajoMasterClientProtocol_2eproto() {
  protobuf_AddDesc_TajoMasterClientProtocol_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "TajoMasterClientProtocol.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_TajoMasterClientProtocol_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_TajoMasterClientProtocol_2eproto() {
}

void protobuf_AddDesc_TajoMasterClientProtocol_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_tajo_5fprotos_2eproto();
  ::protobuf_AddDesc_TajoIdProtos_2eproto();
  ::protobuf_AddDesc_CatalogProtos_2eproto();
  ::protobuf_AddDesc_PrimitiveProtos_2eproto();
  ::tajo::client::protobuf_AddDesc_ClientProtos_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\036TajoMasterClientProtocol.proto\022\013tajo.c"
    "lient\032\021tajo_protos.proto\032\022TajoIdProtos.p"
    "roto\032\023CatalogProtos.proto\032\025PrimitiveProt"
    "os.proto\032\022ClientProtos.proto2\304\025\n\037TajoMas"
    "terClientProtocolService\022V\n\rcreateSessio"
    "n\022!.tajo.client.CreateSessionRequest\032\".t"
    "ajo.client.CreateSessionResponse\022.\n\rremo"
    "veSession\022\017.SessionIdProto\032\014.ReturnState"
    "\022g\n\026updateSessionVariables\022).tajo.client"
    ".UpdateSessionVariableRequest\032\".tajo.cli"
    "ent.SessionUpdateResponse\022G\n\024existSessio"
    "nVariable\022!.tajo.client.SessionedStringP"
    "roto\032\014.ReturnState\022H\n\022getSessionVariable"
    "\022!.tajo.client.SessionedStringProto\032\017.St"
    "ringResponse\022\?\n\026getAllSessionVariables\022\017"
    ".SessionIdProto\032\024.KeyValueSetResponse\022J\n"
    "\013submitQuery\022\031.tajo.client.QueryRequest\032"
    " .tajo.client.SubmitQueryResponse\022J\n\013upd"
    "ateQuery\022\031.tajo.client.QueryRequest\032 .ta"
    "jo.client.UpdateQueryResponse\022Y\n\016getQuer"
    "yResult\022\".tajo.client.GetQueryResultRequ"
    "est\032#.tajo.client.GetQueryResultResponse"
    "\022e\n\022getQueryResultData\022&.tajo.client.Get"
    "QueryResultDataRequest\032\'.tajo.client.Get"
    "QueryResultDataResponse\022Y\n\016getQueryStatu"
    "s\022\".tajo.client.GetQueryStatusRequest\032#."
    "tajo.client.GetQueryStatusResponse\022I\n\023ge"
    "tRunningQueryList\022\017.SessionIdProto\032!.taj"
    "o.client.GetQueryListResponse\022J\n\024getFini"
    "shedQueryList\022\017.SessionIdProto\032!.tajo.cl"
    "ient.GetQueryListResponse\0226\n\tkillQuery\022\033"
    ".tajo.client.QueryIdRequest\032\014.ReturnStat"
    "e\022Y\n\016getClusterInfo\022\".tajo.client.GetClu"
    "sterInfoRequest\032#.tajo.client.GetCluster"
    "InfoResponse\022A\n\024closeNonForwardQuery\022\033.t"
    "ajo.client.QueryIdRequest\032\014.ReturnState\022"
    "N\n\014getQueryInfo\022\033.tajo.client.QueryIdReq"
    "uest\032!.tajo.client.GetQueryInfoResponse\022"
    "A\n\016createDatabase\022!.tajo.client.Sessione"
    "dStringProto\032\014.ReturnState\022@\n\rexistDatab"
    "ase\022!.tajo.client.SessionedStringProto\032\014"
    ".ReturnState\022\?\n\014dropDatabase\022!.tajo.clie"
    "nt.SessionedStringProto\032\014.ReturnState\0227\n"
    "\017getAllDatabases\022\017.SessionIdProto\032\023.Stri"
    "ngListResponse\0226\n\022getCurrentDatabase\022\017.S"
    "essionIdProto\032\017.StringResponse\022A\n\016select"
    "Database\022!.tajo.client.SessionedStringPr"
    "oto\032\014.ReturnState\022F\n\023createExternalTable"
    "\022\037.tajo.client.CreateTableRequest\032\016.Tabl"
    "eResponse\022=\n\nexistTable\022!.tajo.client.Se"
    "ssionedStringProto\032\014.ReturnState\0228\n\tdrop"
    "Table\022\035.tajo.client.DropTableRequest\032\014.R"
    "eturnState\022F\n\014getTableList\022!.tajo.client"
    ".SessionedStringProto\032\023.StringListRespon"
    "se\022A\n\014getTableDesc\022!.tajo.client.Session"
    "edStringProto\032\016.TableResponse\022K\n\017getFunc"
    "tionList\022!.tajo.client.SessionedStringPr"
    "oto\032\025.FunctionListResponse\022U\n\030getPartiti"
    "onsByTableName\022!.tajo.client.SessionedSt"
    "ringProto\032\026.PartitionListResponse\022E\n\020get"
    "IndexWithName\022!.tajo.client.SessionedStr"
    "ingProto\032\016.IndexResponse\022E\n\022existIndexWi"
    "thName\022!.tajo.client.SessionedStringProt"
    "o\032\014.ReturnState\022K\n\022getIndexesForTable\022!."
    "tajo.client.SessionedStringProto\032\022.Index"
    "ListResponse\022G\n\024existIndexesForTable\022!.t"
    "ajo.client.SessionedStringProto\032\014.Return"
    "State\022N\n\023getIndexWithColumns\022\'.tajo.clie"
    "nt.GetIndexWithColumnsRequest\032\016.IndexRes"
    "ponse\022N\n\025existIndexWithColumns\022\'.tajo.cl"
    "ient.GetIndexWithColumnsRequest\032\014.Return"
    "State\022<\n\tdropIndex\022!.tajo.client.Session"
    "edStringProto\032\014.ReturnStateB5\n\023org.apach"
    "e.tajo.ipcB\030TajoMasterClientProtocol\210\001\001\240"
    "\001\001", 2962);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TajoMasterClientProtocol.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_TajoMasterClientProtocol_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_TajoMasterClientProtocol_2eproto {
  StaticDescriptorInitializer_TajoMasterClientProtocol_2eproto() {
    protobuf_AddDesc_TajoMasterClientProtocol_2eproto();
  }
} static_descriptor_initializer_TajoMasterClientProtocol_2eproto_;

// @@protoc_insertion_point(namespace_scope)

}  // namespace client
}  // namespace tajo

// @@protoc_insertion_point(global_scope)
